# Site settings
title: Maxime Bokobza
exclude: ['README.md', 'CNAME']
email: max@codehawks.eu
baseurl: ""
url: "http://bokobza.me"
twitter_username: maxbok
github_username: maxbok

# Build settings
markdown: kramdown

permalink: /:title/
defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/fr
    values:
      layout: default
      lang: fr

t:
  years_old: years old
  software_engineer: Software Engineer
  experience: Work experience
  education: Education
  side_projects: Side projects
  skills: Skills
  hobbies: Hobbies
